global using Microsoft.EntityFrameworkCore;
global using static System.ArgumentException;
global using static System.ArgumentNullException;
global using static System.ArgumentOutOfRangeException;
global using Ardalis.Specification;
global using FluentValidation;
global using ErrorOr;
global using Vogen;
global using Azure.Search.Documents;
global using Azure.Search.Documents.Models;
global using ScenariosWHwar.API.Core.Common.Interfaces;
